on: workflow_dispatch

jobs:
  ascii-job:
    runs-on: ubuntu-latest
    name: A job to print word as ascii art
    steps:
      - name: ASCII art action step
        id: art
        uses: Spots87/ascii-action@v1
        with:
          my-text: 'Neato'
