on: workflow_dispatch

jobs:
  composite-job:
    runs-on: ubuntu-latest
    name: composite
    steps:
      - name: Testing wrapping other custom actions together
        id: composite
        uses: Spots87/composite-actions-practice@v1
        with:
          my-text: 'Neato'
          user-name: 'Guy'
          user-age: '45'
          user-email: 'joeCool@example.com'